### ISSUE TITLE
Figure out a good name for this plugin

### ISSUE THREAD

**Issue by sc0ttkclark** [DavidCramer/pods-frontier#1]
@pglewis @Shelob9 @Desertsnowman

This plugin is pretty cool, check out the screenshots and give it a run at some point, @Desertsnowman will post the link to his post about it.

We are just about ready to put this out, but we still need to figure out a good name for it. Does anyone have any thoughts?

It does three things very nicely:
- Advanced Templating, with assets and autocompletion magic loops and tags
- Form Building with multiple columns
- Layout management / builder, which can be called by the Advanced Templating, and include embedded form(s)

**Comment by DavidCramer** [comment]
Screenshots and details can be found here http://cramer.co.za/pods-framework-front-end-suite/

**Comment by Shelob9** [comment]
@Desertsnowman This === awesome.

@sc0ttkclark Is the metabox manager still happening and being called the metabox manager?

If so, for consistency's sake I vote for Display Manager or Front-end Display Manager

**Comment by sc0ttkclark** [comment]
Metabox manager will be labeled as 'Groups' in the admin, but yeah it's happening in Pods 2.4

**Comment by sc0ttkclark** [comment]
My ideas:
- Pods Display Suite
- Pods Advanced Templates
- Pods Template Builder

**Comment by Shelob9** [comment]
OK. Then I vote for Pods Display Suite or anything that doesn't use the word 'template' since I have enough fun differentiating between Pods Templates, WordPress theme templates and the Pods Templates component already.

**Comment by DavidCramer** [comment]
More options:
Pods Front
Pods Front-end Designer
Pod Views

**Comment by sc0ttkclark** [comment]
I like something with Front on it, that sounds good.

More ideas:
- Pods Frontend Builder
- Pods Frontier :)
- Pods Layout Builder
- Pods Layouts

**Comment by DavidCramer** [comment]
I'm kinda liking Frontier :D

**Comment by KoenRijpstra** [comment]
+1 Pods Frontier
- Pods Frontal :P

**Comment by Shelob9** [comment]
Pods, The New Frontier, to boldly go were no WordPress development
framework has gone before.

**Comment by sc0ttkclark** [comment]
Really liking **Pods Frontier**, sounds like a really good step towards branding this as what it is :)

**Comment by Shelob9** [comment]
+1 especially if the announcement about it comes with a picture of Scott dressed up as Caption Kirk.

**Comment by sc0ttkclark** [comment]
May need to do a group photo for this one...

**Comment by sc0ttkclark** [comment]
Frontier sounds really good for this, let's pull the trigger and do it!

Please Note: @curtismchale @davidj7 @domnusca @fastone @jchristopher @mgibbs189 @KoenRijpstra @kamilgrzegorczyk @bonsak @naomicbush @pglewis @Ramoonus @shelob9 @unknownnf 

This means the repo location will be changing from pods-framework/pods-display-suite to pods-framework/pods-frontier

**Comment by sc0ttkclark** [comment]
OK, it has been renamed!

https://github.com/pods-framework/pods-frontier
