### ISSUE TITLE
In template editor, text is cut off on the right side

### ISSUE THREAD

**Issue by Shelob9** [DavidCramer/pods-frontier#11]
When editing templates the first three characters in a line are cut off. 
I am testing with Pods 2.3.18/ WP 3.8alpha in Chrome for Mac (OSX10.9)

![screen shot 2013-11-13 at 11 53 33 pm](https://f.cloud.github.com/assets/1994311/1538510/ed286808-4ce8-11e3-88ec-620801515256.png)

**Comment by DavidCramer** [comment]
I totally missed that. Thanks.

**Comment by tripflex** [comment]
Confirmed this as well, both in Chrome and Firefox ... but, it's cut off on the left side :)
