### ISSUE TITLE
Layout editor accordion cutoff/scroll

### ISSUE THREAD

**Issue by tripflex** [DavidCramer/pods-frontier#16]
Layout editor uses what looks like jquery ui accordion, but it should probably be updated to be responsive based on browser size.

Preview:
https://smyl.es/img/Selection-1731x387-37.png

**Comment by DavidCramer** [comment]
UI changes in the upcoming beta has moved these to core metaboxes which inherit the responsive nature of WordPress.

Thanks for spotting it though!
