### ISSUE TITLE
Review UI

### ISSUE THREAD

**Issue by sc0ttkclark** [DavidCramer/pods-frontier#2]
There may be ways to bring the UI closer to WP core UI in certain areas

**Comment by DavidCramer** [comment]
My current UI cleanup is all about making it closer to WordPress core.

**Comment by Shelob9** [comment]
@Desertsnowman Have you seen this: https://github.com/helenhousandi/wp-style-guide ? Might be useful.

**Comment by sc0ttkclark** [comment]
@Desertsnowman great, wasn't sure if you were planning on doing any of that in this initial release so figured I'd take the pressure off and target 2.0 but 1.0 would be great.

**Comment by DavidCramer** [comment]
When I make new plugins I use my own little prototyping framework which allows me not to worry to much about the interface and focus on functionality. After function comes form. I know all that it can do and I can start cleaning up the UI to make controlling it easier.

**Comment by DavidCramer** [comment]
@Shelob9 I have seen it and it is very useful, thanks.

**Comment by DavidCramer** [comment]
I'm breaking the components down to custom post types:
- Views
- Forms
- Layouts

This will bring the UI to core and make things much easier to manage.
