### ISSUE TITLE
[IF] issue

### ISSUE THREAD

**Issue by Shelob9** [DavidCramer/pods-frontier#25]
In this case the field 'wys' is a WYSIWYG field. This is my template:

``` html
{@wys}
[if wys]
Label: {@wys}
[/if]
```

If there is no value for 'wys' I get no output, which is expected. If I add "foo" to wys field, I get:

``` html
foo
Label: {@wys}
```

The tag is not converted inside of the if block.

Ability to show a label for a field, only if field has a value is a very common request.

**Comment by DavidCramer** [comment]
The commands are actually a part of the template component as per #14 
I'll replicate this to the Pods issues and then fix.

**Comment by DavidCramer** [comment]
Is this still an issue?

**Comment by Shelob9** [comment]
Sorry, this is fixed. I am closing now.
