### ISSUE TITLE
Frontiers admin layout broken

### ISSUE THREAD

**Issue by carlosrovira** [DavidCramer/pods-frontier#30]
I'm new to this plugin and just installed to test it since I'm very interested. I'm facing what seems a huge problem since make it almost unable to manage the plugin in an easy way.

Frontier admin shows form elements behind others making very difficult to edit the top ones
. You end imagining what box you selected since you can't read the label. I upload a screen shot

![captura de pantalla 2014-06-23 a la s 12 28 04](https://cloud.githubusercontent.com/assets/1701640/3356566/6c948756-fac3-11e3-8f8c-40bec301a91d.png)

another problem is that if we change the admin css the layout breaks:

![captura de pantalla 2014-06-23 a la s 12 47 51](https://cloud.githubusercontent.com/assets/1701640/3356603/fe81ab26-fac3-11e3-961d-6a1e8280f48f.png)

**Comment by Shelob9** [comment]
@carlosrovira Thanks for this report. As you know, this plugin is still under development and these sorts of reports are very helpful for us as we work to get this plugin finished.

Can you please let us know what browser and operating system, as well as version of Pods and WordPress that you are experiencing this issue with?

**Comment by carlosrovira** [comment]
Hi Josh,

I'm on latest OSX 10.9.3, latest Pods 2.4.2 and latest wordpress 3.9.1

I'm very interested in this plugin so I'll be testing and reporting what I see to help improve and reach the stable version.

Thanks for such great piece of software!

Carlos

**Comment by Shelob9** [comment]
Carlos,

Thanks for the additional information. What browser are you testing in? I don't see these issues with latest Chrome on OSX 10.9.2

**Comment by carlosrovira** [comment]
Hi Josh,

just tested on OS X 10.9.3 with latest Safari (Versión 7.0.4 (9537.76.4)), Chrome (Versión 35.0.1916.153) and Firefox (Version 30.0) and problem shows in all browsers. Don't think that OS X version be significative since all browsers are behaving in the same way in my machine.

I'll try to test in other machine other than this as I have some other available

**Comment by Shelob9** [comment]
Carlos-

Can you please share your Pods Debug Info form Pods Admin->Settings so I can see if there is anything there that might indicate why this is happening on your end, but not for me?

Also, have you tried without any other plugins active and with the default theme active to see if this might be a conflict with something you are running on your site?

Thanks for all of your patience and help.

-Josh

**Comment by carlosrovira** [comment]
Hi Josh,

I sent in private mail the debug info. In the other hand I didn't try it without plugins. Only disabled the a plugin for admin theme since it could be a potential problem and the root of such problem, but as I state in the screen shots it wasn't relevant in this case so I enable it again.

give the debug info, do you think I should disable all and try?

**Comment by Shelob9** [comment]
@carlosrovira I saw that email. I'd definitely recommend trying without any other plugins active. I bet one or your theme is causing the conflict and it would be helpful to know what that is. Nothing in the rest of the debug info jumps out at me, looks like you're running almost exactly the same base setup as me, possibly the same. VVV?

**Comment by carlosrovira** [comment]
Hi Josh,

I disable all plugins and get it working. So I was activating one by one and refreshing to get the problematic plugin. The result was: WPML Multilingual CMS 3.1.5
luckily this WPML plugiin could be removed in my installation since it's of no use, but other using WPML could have problem. I don't know if this should be reported to WPML or is a frontier problem. Maybe you could get some light here.

Thanks

**Comment by Shelob9** [comment]
Thanks for doing this investigation work. I have opened a new issue to address the conflict with WPML #32 and will do some testing with it later to day to see if I can get to the bottom of this.
