### ISSUE TITLE
Template html editor magictag autocomplete bug

### ISSUE THREAD

**Issue by bonsak** [DavidCramer/pods-frontier#4]
I can't use backspace on righthand curly-brackets when editing in the html template edit screen. 
Test: Enter "{@post_title} and try to delete the right most bracket with your backspace key. The editor re-inserts the "}" immediately after its deleted.

**Comment by DavidCramer** [comment]
The autocomplete is a little obsessive. If there is only a single match it autocompletes it.
I'll put in some intent detection to disable autocomplete on the backspace key.

**Comment by bonsak** [comment]
Sweet
