### ISSUE TITLE
Create New Frontier

### ISSUE THREAD

**Issue by qrahaman** [DavidCramer/pods-frontier#43]
Hello,

Per the readme document, I am trying to create a new Frontier but do not see a way to do that through the Pods menu.  If you would like access to my site, I can provide you with credentials (email needed).  Here's the Settings info and I've included a screenshot of the menu that I see:

WordPress Version: 3.9.2

PHP Version: 5.4.31-1~dotdeb.0

MySQL Version: 5.5.5

Server Software: nginx/1.7.4

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/7.0.6 Safari/537.78.2

Session Save Path: 10.210.0.235:6379

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

WPDB Prefix: cdmcie_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Fourteen

Currently Active Plugins:

Akismet: 3.0.2
Pods - Custom Content Types and Fields: 2.4.3
Pods Frontier Auto Template: 1.1.2
WP-FB-AutoConnect: 4.0.2

![screen shot 2014-08-27 at 4 31 00 pm](https://cloud.githubusercontent.com/assets/1299653/4069188/752e5254-2e42-11e4-9426-26cbb86a3fd8.png)

**Comment by Shelob9** [comment]
You're debug information does not show the Pods Frontier plugin as active. It is different from Pods Frontier Auto Template. I know those two names are confusing--that was a mistake on our part. The two plugins will likely be merged eventually, if not Auto Template will need to be renamed.

**Comment by qrahaman** [comment]
Hello Josh,

Thanks.  Is it named something different... I cannot find it in the WP directory.  Or can I download it from Git?

Quint A. Rahaman, Jr.
Telesis Academy
734.657.7740

**Comment by qrahaman** [comment]
Never mind... I got it from Git.  Thanks!

Quint A. Rahaman, Jr.
Telesis Academy
734.657.7740

**Comment by Shelob9** [comment]
@qrahaman I'm glad to see that you found it. Please let us know if there is anything else we can do to help.
