### ISSUE TITLE
Error: TypeError: wp.mce is undefined 

### ISSUE THREAD

**Issue by quasel** [DavidCramer/pods-frontier#46]
Tested with Wordpress 4.0 - no plugins activated beside Pods/Frontier - you cant add/edit anything in frontier - deactivate the new live_preview actions/scripts back to normal ;)

Fehler: TypeError: wp.mce is undefined

**Comment by djm56** [comment]
I have the exact same issue as above, I dont understand the deactivate live_preview please could you explain better. I cannot add or edit.

**Comment by djm56** [comment]
Ok I figured it out had to comment out live_preview in pods-frontier-templates.php
Line 152  //wp_enqueue_script( $this->plugin_slug . '-live-preview', $this->get_url( 'assets/j...........
Now it is working again, dont know what I did but its working.

**Comment by quasel** [comment]
i guess same issue https://github.com/pods-framework/pods-frontier/issues/50
