### ISSUE TITLE
editing a frontier form - Base Pod on load isnt set correct

### ISSUE THREAD

**Issue by quasel** [DavidCramer/pods-frontier#47]
Edit a Frontier form - Base Pod is not loaded correct ->
on save it saves the selcted Base Pod althoug no change from the user involved...

**Comment by quasel** [comment]
moved into pods core ;)

**Comment by DavidCramer** [comment]
@quasel wow! history right there!

**Comment by quasel** [comment]
yes indeed - a long time ago :D
