### ISSUE TITLE
[each][/each] order by post publish date

### ISSUE THREAD

**Issue by alexedev** [DavidCramer/pods-frontier#49]
Hello. 
How can I rewrite the code to have posts ordered by publish date when I use [each][/each]?

**Comment by Shelob9** [comment]
Are you asking how to rewrite Frontier itself to have an orderby param for the each loop? Because, that would be neat, though it would require Pods 2.4.4 or later, as most recent versions had a bug preventing passing parameters to `Pods::find()`.

I'm not sure exactly how this would be done, by suspect the answer is here:
https://github.com/pods-framework/pods/blob/2.x/components/Templates/includes/functions-view_template.php#L214-L275

**Comment by alexedev** [comment]
Yes. I already looked at that function but did not succeed with the order change, because I'm not good with php(that is why I use pods-frontier advanced markup ;-) ) I think the order should be indicated somehow in $entries variable. Could you please help with it?

**Comment by alexedev** [comment]
Or maybe it is possible somewhere to rewrite the default order for all pods entries which is now by title?

**Comment by quasel** [comment]
Just a quick idea - didn't use frontier - but depends on CPT/ACT etc but you can set a default orderby  - for relationship fields -  pods admin -> pod -> field -> Additional Field Options ->   Customized ORDER BY: 

e.g. - date DESC  should do the trick

**Comment by alexedev** [comment]
@quasel that is exactly what I wanted, thanx!
Anyway, it would be cool to write smth like 
[each pod_relatedpod where="" orderby=""]some code here[/each] as is possible with [pods ....] 

I think the issue can be closed now. Thank you for your time!

**Comment by quasel** [comment]
You are welcome ;) - yes something like that could indeed be useful.
or go create a pod page with customized ->find() an call the template from there pods()->template();  ;) but it involves a little bit more php

**Comment by alexedev** [comment]
wanted to add that when you edit the relationship field that you want to order by date
in _pods admin -> pod -> field -> Additional Field Options -> Customized ORDER BY_
you need to add not **date DESC** but **'date DESC'**
otherwise you will get the error _Unknown column date in ‘order clause’_ when editing a pod

**Comment by sc0ttkclark** [comment]
Actually, if you've created a field called "date" that's a MySQL reserved word. You should use backticks instead:

```
t.`date` DESC
```

**Comment by alexedev** [comment]
@sc0ttkclark no, it is not the field but parameter for **orderby**
