### ISSUE TITLE
Display single record in template inside layout

### ISSUE THREAD

**Issue by bonsak** [DavidCramer/pods-frontier#5]
With a template inside a layout, i specify a single item-id on the "Specific item"-tab but it doesn't show anything on the front-end. It works if i insert only the template on a page like this: [displaypod dp=5276d94943a90 id=3038] or if i use WHERE on the query-tab and set it to id=3038

**Comment by DavidCramer** [comment]
Thanks, I'll take a look and sort it out.

**Comment by DavidCramer** [comment]
Merged fully with the standard templates.
