### ISSUE TITLE
JS error on shortcode-live-preview.js

### ISSUE THREAD

**Issue by carherbl** [DavidCramer/pods-frontier#50]
Hi!

first of all, thanks for developing such an interesting freature for pods, which is also a must in every WP installation.

I've just installed the pluggin, but I got some js error in shortcode-live-preview.js, which is also breaking the js WP funcionalities.

The error I get:

![image](https://cloud.githubusercontent.com/assets/9322909/5316868/fff70e66-7c90-11e4-8243-9427f6781e16.png)

which contains:
<a href="https://cloud.githubusercontent.com/assets/9322909/5316877/1f4d4a78-7c91-11e4-8737-56b71491077b.png">
<img src="https://cloud.githubusercontent.com/assets/9322909/5316877/1f4d4a78-7c91-11e4-8737-56b71491077b.png" width="350" ></a>
...

I am quite new in WP, so I'm not sure if that is my fault or something else, sorry if that is the case. 
I'm running Pods 2.3.4 with WP 3.9.2

Thanks!

**Comment by DavidCramer** [comment]
Thanks, I found the issue will correct it asap

**Comment by Shelob9** [comment]
@Desertsnowman Isn't this the same issue I showed you that one time in Caldera Forms?

**Comment by mark2685** [comment]
I'm seeing this error as well, any update on this, @Desertsnowman ?

**Comment by Shelob9** [comment]
@mark2685 The simplest solution to this issue is to update your WordPress version. This shouldn't be an issue in 4.0 and 4.1. The issue is related to changes in how MCE works in 4.0.

**Comment by mark2685** [comment]
@Shelob9 I'm currently on 4.1.

Pods - Version 2.5
Pods Frontier - Version 1.000
Pods Frontier Auto Template - Version 1.1.2

**Comment by Shelob9** [comment]
Hmmm. Then this isn't the issue I suspected. I will be talking about Frontier with @Desertsnowman this week and will make sure we discuss this issue.
