### ISSUE TITLE
Template confusion

### ISSUE THREAD

**Issue by bonsak** [DavidCramer/pods-frontier#6]
Are Templates in this plugin and Templates in Pods supposed to be interchangeable? Its a little confusing that both this plugin and Pods have an entity of "Templates". It took me a little while to realize that they are not the same thing. Maybe it should be differentiated?

**Comment by DavidCramer** [comment]
The prototype of this plugin fed off the pods templates, but with this version, they are separate.

I think you have a point, this needs to be more defined to indicate its a separate item.

any suggestions?

**Comment by bonsak** [comment]
Maybe just an abbreviation of the eventual name of this plugin as a prefix to "template" is sufficient, until they can be used interchangeable? PDS-template, PF-template? :)

**Comment by sc0ttkclark** [comment]
- Frontier Template
- Frontier View

**Comment by bonsak** [comment]
Frontier Template +1

**Comment by Shelob9** [comment]
I'm still worried about having to difrentiate between Pods Templates,
templates in themes and now Frontier Templates.

For that reason I vote for calling these 'Views'

**Comment by DavidCramer** [comment]
+1 Frontier View

**Comment by sc0ttkclark** [comment]
We went with this terminology:
- Frontier Views (the templates)
- Frontier Layouts (the layouts that can embed views and forms and other element types like HTML)
- Frontier Forms (custom Pod forms)
